package com.beeftech.database

import androidx.sqlite.db.SupportSQLiteDatabase

/*
 * Seed rows for roles (fixes FK crash: users.role -> roles.role_id).
 *
 * role_id values are fixed, not autogenerated, to match the server-issued
 * role ints from the login API (see README.md:191-194 and
 * backend DevUserSeeder.kt). Used by BeefTechDatabase.SEED_CALLBACK's
 * onCreate (fresh installs) and onOpen (backfills any device that already
 * migrated with an empty roles table), and also called as the first
 * statement of MIGRATION_14_16 itself (R0.4): that migration reads `roles`
 * while cleaning up farmer_roles orphans, and onOpen doesn't run until every
 * migration has finished, so `roles` would otherwise still be empty when
 * 14->16 runs and every farmer role would look orphaned. INSERT OR IGNORE
 * keeps it safe to run from all three places.
 *
 * TODO: if the backend ever issues a role id outside 1/2/3, this crash
 * will recur for that id -- there is no real roles-sync mechanism.
 */
object RoleSeed {

    /* role_id to role_name, per README.md:191-194. */
    val ROLES: List<Pair<Long, String>> = listOf(
        1L to "Administrator",
        2L to "Farm Manager",
        3L to "Worker / User"
    )

    fun execute(db: SupportSQLiteDatabase) {
        ROLES.forEach { (roleId, roleName) ->
            db.execSQL(
                "INSERT OR IGNORE INTO `roles` (`role_id`, `role_name`) VALUES (?, ?)",
                arrayOf<Any>(roleId, roleName)
            )
        }
    }
}
