package com.beeftech.database

import androidx.sqlite.db.SupportSQLiteDatabase

/*
 * Seed rows for roles (fixes FK crash: users.role -> roles.role_id).
 *
 * role_id values are fixed, not autogenerated, to match the server-issued
 * role ints from the login API (see README.md:191-194 and
 * backend DevUserSeeder.kt). Used by BeefTechDatabase.SEED_CALLBACK only:
 * onCreate covers fresh installs; onOpen retroactively backfills devices
 * already migrated to version 16/17 with an empty roles table. Not called
 * from any Migration -- MIGRATION_14_16 already shipped and must not be
 * edited. INSERT OR IGNORE keeps it safe to run on every onOpen.
 *
 * TODO: if the backend ever issues a role id outside 1/2/3, this crash
 * will recur for that id -- there is no real roles-sync mechanism.
 */
object RoleSeed {

    /* role_id to role_name, per README.md:191-194. */
    val ROLES: List<Pair<Long, String>> = listOf(
        1L to "Administrator",
        2L to "Farm Manager",
        3L to "Worker / User"
    )

    fun execute(db: SupportSQLiteDatabase) {
        ROLES.forEach { (roleId, roleName) ->
            db.execSQL(
                "INSERT OR IGNORE INTO `roles` (`role_id`, `role_name`) VALUES (?, ?)",
                arrayOf<Any>(roleId, roleName)
            )
        }
    }
}
