/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.7.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "beeftech"

// Include Android modules
include(":android:app")
include(":android:authentication")
include(":android:calf-registration")
include(":android:database")
include(":android:farmer-registration")
include(":android:farm-traceability")
include(":android:feed-crib")

// Include Backend modules
include(":backend:api")
include(":backend:authentication")
include(":backend:sync")